api_version = "2026-01"

[[extensions]]
name = "Free Item Auto Discount"
handle = "discount-function-free-item"
type = "function"
uid = "4aee1596-cbdf-5434-03b7-17a56f746f6ced822663"
description = "Automatically applies 100% discount to cheapest 'Free Item' product when cart subtotal is $500+"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.capabilities]
  autoapply = true
