# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0357131818b827a9931726cb84a81166"
name = "discount-product-demo"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_products,read_product_listings,write_shipping,write_payment_gateways,read_orders,write_cart_transforms"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
